### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by xiaonh** [mobb111/rudygen-master#2]
line 3673
    print '  ', words1, '  ' , data[0] , ' ', data[1], '=', data[2]
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('  ', words1, '  ' , data[0] , ' ', data[1], '=', data[2])?

**Comment by mobb111** [comment]
what python u use?

**Comment by mobb111** [comment]
try now new update rudygen.py

**Comment by xiaonh** [comment]
last version of python, 3.7.0

same error

rudygen.py", line 167
    print '  ', words1, '  ' , data[0] , ' ', data[1], '=', data[2]
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('  ', words1, '  ' , data[0] , ' ', data[1], '=', data[2])?

**Comment by Toroop78** [comment]
> строка 3673 
> print '', words1, '', data [0], '', data [1], '=', data [2] 
> ^ 
> SyntaxError: Отсутствует круглые скобки при вызове 'print'. Вы имели в виду print ('', words1, '', data [0], '', data [1], '=', data [2])?

run Python2.7

**Comment by Toroop78** [comment]
compile .exe https://yadi.sk/d/PV5FozcTSsL6Ow

**Comment by mobb111** [comment]
use python 3.4.0 or 2.7.13
