### ISSUE TITLE
Issue codecs

### ISSUE THREAD

**Issue by Toroop78** [mobb111/rudygen-master#3]
Could not find a version that satisfies the requirement codecs (from -r requirements.txt (line 4)) (from versions: )
No matching distribution found for codecs (from -r requirements.txt (line 4))

**Comment by mobb111** [comment]
ok u dont need codecs i need to remove that codecs come with python

**Comment by mobb111** [comment]
now i added memonic words bip39 now ist better

**Comment by mobb111** [comment]
try now i update rudygen.py

**Comment by Toroop78** [comment]
now getting an error: 
File "rudygen.py", line 167
    print '  ', words1, '  ' , data[0] , ' ', data[1], '=', data[2]
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('  ', words1, '  ' , data[0] , ' ', data[1], '=', data[2])? 

Python 3.7 Windows10

**Comment by Toroop78** [comment]
works great on Python2.7

**Comment by mobb111** [comment]
that is becose ip im working on that to if u intresed for another generator is not publish jet prototype rudygen
