### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bronxanarchy** [mobb111/rudygen-master#4]
File "rudygen.py", line 121, in <module>
    passp1_sha256 = hashlib.sha256(binascii.hexlify(list1)).hexdigest()

TypeError: a bytes-like object is required, not 'str'

**Comment by Bronxanarchy** [comment]
hi mob, 3.X

mobb <notifications@github.com>, 21 Eyl 2018 Cum, 17:26 tarihinde şunu
yazdı:

**Comment by Bronxanarchy** [comment]
python version 3.6.5

**Comment by mobb111** [comment]
ok i use 3.4.0 and wit that is working great

**Comment by mobb111** [comment]
tomorow i will upload new hack better then rudygen thata is working i finish it

**Comment by mobb111** [comment]
or mybe now

**Comment by mobb111** [comment]
im working on that to that program will read a file

**Comment by mobb111** [comment]
https://github.com/mobb111/rubygen

**Comment by mobb111** [comment]
here it is better version
