### ISSUE TITLE
line 161, in <module>

### ISSUE THREAD

**Issue by granula** [mobb111/rudygen-master#5]
Python 2.7
Works normally 10 minutes and then an error.

Traceback (most recent call last):
  File "rudygen.py", line 161, in <module>
    balance = int(API.text)
ValueError: invalid literal for int() with base 10: 'Bitcoin JSON-RPC: Work queue depth exceeded. Code:429'

Traceback (most recent call last):
  File "rudygen.py", line 161, in <module>
    balance = int(API.text)
ValueError: invalid literal for int() with base 10: '<!DOCTYPE html>   <!--[if IE 8]>    <html class="no-'

Python 3.4x not working.

**Comment by mobb111** [comment]
ok api is problem i advise u to go to other my respitory rubygen-master vhere is prototype and is working great, now im working on hack that will read directly from the txt or lst file, this respitory need more working
